apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-repo-runner
  labels:
spec:
  replicas: 3
  template:
    spec:
      priorityClassName: "system-node-critical"
      nodeSelector:
        kubernetes.io/os: "linux"
      sidecarContainers:
        - name: python
          image: centos:7.9.2009
          env:
            - name: TZ
              value: Asia/Shanghai
          securityContext:
            runAsUser: 0
      repository: BinchenQ/python
      # runs-on 
      labels:
        - python
        - centos